### ISSUE TITLE
UX: Yeclite wallet stopped working

### ISSUE THREAD

**Issue by newbieknowsnothing** [ycashfoundation/ycash#33]
I mined about 2000 Ycash and now the yeclite wallet will not send or recieve  I get this error on the computer that had the wallet first when I try to send : 
   error code - Error: SendResponse { error_code: -26, error_message: "16: bad-txns-sapling-spend-description-invalid" }  
So I installed the wallet on a different computer and used the pass words to restore it and that computer gets this error  : 
    Error: SendResponse { error_code: -26, error_message: "tx-expiring-soon: expiryheight is 1122901 but should be at least 1122904 to avoid transaction expiring soon" }

**Comment by hloo** [comment]
YecLite does not work right now due to the January network upgrades. I'm working on trying to update it this weekend.

**Comment by newbieknowsnothing** [comment]
Thank You for the explanation.

**Comment by newbieknowsnothing** [comment]
Is there an ETA on when the wallet will work again ?

**Comment by hloo** [comment]
I apologize for the delay. It should be fixed by April 1. In the meantime, consider importing your seed into YWallet: https://hhanh00.github.io/zwallet/.

I'm going to close this issue, since this is actually the ycashd repository, not the YecLite repository. Feel free to file additional YecLite issues here: https://github.com/yecdev/yeclite.

**Comment by hloo** [comment]
@newbieknowsnothing I will message you here when the update is ready.

**Comment by newbieknowsnothing** [comment]
Thanks for the Ywallet advice.  I didn't know You could do that. Now I can
start mining Ycash again. I plan to hold it for years if thats what it
takes.
With the 21M cap, I think It can become quite valuable with just a little
wider acceptance.
                Thank You for your help,           Brian
